"""initial migrations

Revision ID: fc46ef86c1a4
Revises: 
Create Date: 2023-05-21 16:17:49.600530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc46ef86c1a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waybill_no', sa.String(length=255), nullable=False),
    sa.Column('ecommerce_company', sa.String(length=255), nullable=False),
    sa.Column('reciepient_name', sa.String(length=255), nullable=False),
    sa.Column('reciepient_email', sa.String(length=255), nullable=False),
    sa.Column('reciepient_phone', sa.String(length=255), nullable=False),
    sa.Column('reciepient_address', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('waybill_no'),
    schema='dts'
    )
    op.create_table('tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('dispatcher_name', sa.String(length=255), nullable=False),
    sa.Column('package_status', postgresql.ENUM('PICKED_UP', 'IN_TRANSIT', 'WAREHOUSE', 'DELIVERED', name='package_status'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['dts.shipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='dts'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker', schema='dts')
    op.drop_table('shipment', schema='dts')
    # ### end Alembic commands ###
