name: Test API

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        sudo docker system prune -a -f
        docker pull postgres
        sudo docker run --name postgresql -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_USER=yemicode -d postgres
        sudo docker run --name redis_db -p 6379:6379 -d redis
        
        cd api/
        pip install -r requirements.txt

        export FLASK_APP='dts:create_app("development")'

        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        export DATABASE_URL=${{ secrets.DATABASE_URL }}

        export REDIS_URI="redis://localhost:6379/0"

        export PORT=5000
        export DEVELOPMENT_MODE=development

        alembic revision --autogenerate -m "initial migrations"
        alembic upgrade head

        pytest -vv
